# Generated by Django 4.1.1 on 2022-10-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='tanggal_lahir',
            new_name='jabatan',
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='tenaga_pendidik',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='tenaga_pendidik',
            name='tanggal_lahir',
        ),
    ]
