# Generated by Django 4.1.1 on 2022-10-06 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0002_rename_nip_mahasiswa_nim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosen',
            old_name='tanggal_lahir',
            new_name='jabatan',
        ),
    ]
