# Generated by Django 4.1.1 on 2022-10-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0004_remove_dosen_alamat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='tenaga_pendidik',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='tenaga_pendidik',
            name='tanggal_lahir',
        ),
    ]
